### ISSUE TITLE
use this without runtime - 

### ISSUE THREAD

**Issue by fxfactorial** [AztecProtocol/huff#12]
Hi - 

I want to rewrite one of my contracts into assembly with huff - looking at the contract, it seems like Runtime is necessary for extracting the bytecode (like for the constructor) but it also "runs" the code in the ethereumjs-vm (which is unnecessary for me) 

wondering what a possible workflow for this task would look like (rewriting a contract directly with huff)

**Comment by charlie-g-cowan** [comment]
Not sure how helpful this is as it's been a long time since I've worked on this, but Zac and Laurence wrote a series on how, as an example, an ERC20 could be rewritten in Huff. It might be helpful.
https://medium.com/aztec-protocol/from-zero-to-nowhere-smart-contract-programming-in-huff-1-2-ba2b6de7fa83
https://medium.com/aztec-protocol/from-zero-to-nowhere-smart-contract-programming-in-huff-2-3-5438ef7e5beb
https://medium.com/aztec-protocol/from-zero-to-nowhere-smart-contract-programming-in-huff-3-4-6b347e23d66e
https://medium.com/aztec-protocol/from-zero-to-nowhere-smart-contract-programming-in-huff-4-4-9e6c34648992
